# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- release-1.x.x

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CacheBeta@1
  inputs:
    key: '"$(Agent.OS)" | **/pom.xml'
    path: '$(HOME)/.m2'
  displayName: "Cache mvn packages"
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: |
    cat README.md
